### ISSUE TITLE
Silent failure during sampling of an Excel spreadsheet with blank rows before the data

### ISSUE THREAD

**Issue by craigastill** [ets/tap-spreadsheets-anywhere#52]
## Issue:

When using this tap to read an Excel spreadsheet with a blank row between non-data rows and the table, it fails to parse the file during the sampling discovery stage. This results in: `INFO Processing 0 selected streams from Catalog`.

Mentioned in the [Slack thread](https://meltano.slack.com/archives/C01TCRBBJD7/p1684135547415119).

## Reproduction:

- Spreadsheet with the following format:

  ```
  Title
  Description
  <blank_row>
  <table_header>
  <table_data>
  ...
  Totals
  <blank_row>
  Notes
  ```
- `meltano.yml` snippet (NOTE: hand altered config & output to remove sensitive info):

  ```yaml
  ...
  plugins:
    extractors:
    - name: tap-spreadsheets-anywhere
      variant: ets
      pip_url: git+https://github.com/ets/tap-spreadsheets-anywhere.git
      config:
        tables:
        - path: file:///path/to/spreadsheets/
          name: my_table
          pattern: ".*"
          key_properties: []
          format: excel
          worksheet_name: <sheet_name>
          start_date: '1970-01-01T00:00:00+00:00'
          field_names:
          - "Date"
          - "Description"
          - ...
          skip_initial: 3
  ```
- Install meltano + plugins into a python venv.
- `meltano invoke tap-spreadsheets-anywhere --dev`

  ```shell
  2023-05-15T13:47:56.821676Z [info     ] Environment 'dev' is active
  INFO Generating catalog through sampling.
  INFO Walking /path/to/spreadsheets/.
  INFO Found 1 files.
  INFO Found broken_spreadsheet.xlsx and /path/to/spreadsheets/broken_spreadsheet.xlsx exists True
  INFO Processing 1 resolved objects that met our criteria. Enable debug verbosity logging for more details.
  INFO Sampling broken_spreadsheet.xlsx (1000 records, every 5th record).
  ERROR Unable to write Catalog entry for 'my_table' - it will be skipped due to error tuple index out of range
  INFO Processing 0 selected streams from Catalog
  ```
**EXPECTATION:** `skip_initial` and/or `field_names` would allow the the file to be sampled/read from the line where the table data exists in the Excel file.

## Debugging:

* `excel_handler.generator_wrapper` is throwing an `IndexError` during the sampling phase when on a blank row.
* It doesn't look like `field_names` is used during the sampling phase (Just double checked and it's only used in the `csv_handler.py`).
* The original `skip_initial` changes (https://github.com/ets/tap-spreadsheets-anywhere/pull/37) supported skipping over rows with data in them.
    * To skip over blank rows, it looks like the skip needs to be pushed into the Excel `generator_wrapper`: https://github.com/ets/tap-spreadsheets-anywhere/blob/main/tap_spreadsheets_anywhere/excel_handler.py#L9-L32 before the `header_row` is populated. This avoids the `IndexError` raised when this function parses a blank row.
    * Hacked this change locally and now have Catalogue items: `INFO Wrote 1086 records for stream "my_table".`
