### ISSUE TITLE
Executable 'tap-spreadsheets-anywhere' could not be found

### ISSUE THREAD

**Issue by ReubenFrankel** [ets/tap-spreadsheets-anywhere#78]
I can no longer run `tap-spreadsheets-anywhere` with Meltano:

![image](https://github.com/ets/tap-spreadsheets-anywhere/assets/60552974/6117d484-8221-4299-ba25-5368df362be3)

Most likely this change: https://github.com/ets/tap-spreadsheets-anywhere/commit/78ce8c91bd1ba3b1ed44c00ae89b22c9d94261a9#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L24-L27

**Comment by stul99** [comment]
Any luck resolving this ? I currently have the same issue.

**Comment by ReubenFrankel** [comment]
Yeah, you can pin to the last "good" commit:

```yml
version: 1
default_environment: dev
project_id: c2731ad1-37d5-4d06-b5f3-d27a7d38292e
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-spreadsheets-anywhere
    variant: ets
    pip_url: git+https://github.com/ets/tap-spreadsheets-anywhere.git@e1f321c
```
